# Minimal Oaxaca Demo

This notebook demonstrates a minimal example of running the Oaxaca-Blinder decomposition and printing the results.

In [11]:
%load_ext autoreload
%autoreload 2
import pandas as pd

from oaxaca import Oaxaca

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [12]:
# Load sample data
df = pd.read_csv("sample_data.csv")
df.head()

,age,female,foreign_born,LTHS,high_school,some_college,college,advanced_degree,education_level,ln_real_wage
0,52,0,1,0,1,0,0,0,high_school,2.140066
1,46,1,1,0,1,0,0,0,high_school,NaN
2,31,1,1,0,1,0,0,0,high_school,2.499795
3,35,0,1,0,1,0,0,0,high_school,2.708050
4,19,0,0,0,1,0,0,0,high_school,2.079442

In [13]:
# Initialize and fit the Oaxaca model
oaxaca_model = Oaxaca()

# Fit the model using a simple formula
results = oaxaca_model.fit(
    formula="exp(ln_real_wage) ~ -1 + age + female + C(education_level)", data=df, group_variable="foreign_born"
)

print("Model fitted successfully!")
print(f"Groups: {results.groups_}")

Model fitted successfully!
Groups: [0, 1]

In [14]:
# Run two-fold decomposition
twofold_decomposition = results.two_fold(weights={0: 1.0, 1: 0.0})

In [15]:
# Display detailed summary - shows rich HTML output in Jupyter
twofold_decomposition

OaxacaResults(groups=[0, 1], group_variable='foreign_born')

In [16]:
twofold_decomposition.detailed_contributions()

                                                        explained_detailed  \
variable_group     category
age                age                                           -1.749147
female             female                                        -0.523082
C(education_level) C(education_level)[LTHS]                      -1.527188
                   C(education_level)[advanced_degree]            0.899294
                   C(education_level)[college]                    0.896542
                   C(education_level)[high_school]               -0.583211
                   C(education_level)[some_college]               2.769040

                                                        explained_detailed_pct  \
variable_group     category
age                age                                              -58.003785
female             female                                           -17.346017
C(education_level) C(education_level)[LTHS]                         -50.643366
                   C(education_level)[advanced_degree]               29.821657
                   C(education_level)[college]                       29.730385
                   C(education_level)[high_school]                  -19.339953
                   C(education_level)[some_college]                  91.824645

                                                        unexplained_detailed  \
variable_group     category
age                age                                              7.558531
female             female                                          -1.165265
C(education_level) C(education_level)[LTHS]                        -1.589151
                   C(education_level)[advanced_degree]             -0.404325
                   C(education_level)[college]                      0.233714
                   C(education_level)[high_school]                 -1.295377
                   C(education_level)[some_college]                -0.504801

                                                        unexplained_detailed_pct  \
variable_group     category
age                age                                                250.649793
female             female                                             -38.641548
C(education_level) C(education_level)[LTHS]                           -52.698137
                   C(education_level)[advanced_degree]                -13.407897
                   C(education_level)[college]                          7.750237
                   C(education_level)[high_school]                    -42.956219
                   C(education_level)[some_college]                   -16.739796

                                                           total   total_pct  \
variable_group     category
age                age                                  5.809383  192.646008
female             female                              -1.688347  -55.987565
C(education_level) C(education_level)[LTHS]            -3.116340 -103.341503
                   C(education_level)[advanced_degree]  0.494969   16.413760
                   C(education_level)[college]          1.130256   37.480622
                   C(education_level)[high_school]     -1.878587  -62.296171
                   C(education_level)[some_college]     2.264239   75.084849

                                                       variable_type
variable_group     category
age                age                                    continuous
female             female                                 continuous
C(education_level) C(education_level)[LTHS]              categorical
                   C(education_level)[advanced_degree]   categorical
                   C(education_level)[college]           categorical
                   C(education_level)[high_school]       categorical
                   C(education_level)[some_college]      categorical

In [17]:
threefold_decomposition = results.three_fold()

In [18]:
threefold_decomposition

OaxacaResults(groups=[0, 1], group_variable='foreign_born')